[package]
name = "strand-services-macros"
description = "#[service], #[derive(Store)], #[derive(Data)] and #[derive(Call)] for strand-services"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.6", features = ["full"] }

[lints]
workspace = true
