[package]
name = "strand"
description = "The Strand shell runtime and CLI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
strand-compiler.workspace = true
strand-core.workspace = true
strand-render.workspace = true
strand-scene.workspace = true
strand-services.workspace = true
strand-surface.workspace = true
strand-text.workspace = true
strand-watch.workspace = true

[lints]
workspace = true
